### ISSUE TITLE
Breaking up into individual entries

### ISSUE THREAD

**Issue by bln** [alar-dict/data#1]
Firstly, Thanks a ton for this incredibly useful resource.

I assume that this corpus is not static but become friendly for contribution and crowdsourcing.

Breaking up the monolithic yaml file into individual entries will go a long way in simplifying the contribution of new words and also making updates to existing ones.

A build process could then assemble the corpus into its current form so that the rest of the pieces continue to work the same.

If there is interest in supporting such an approach, I can try to contribute in breaking this down into modular files

**Comment by knadh** [comment]
Thanks @bln. Alar is an authoritative dictionary maintained by its author, so for now, there are no plans to crowd source entries. Once there is clarity, the ideal way would be to build a web UI that's accessible to everyone with a moderation backend. GitHub wouldn't be the best medium for sourcing data contributions.

I have plans to add a submission+moderation system to [dictmaker](https://github.com/knadh/dictmaker) as time permits.

**Comment by bln** [comment]
OK. Thanks a lot for the clarification and best wishes for the next steps
