### ISSUE TITLE
Wow...adbhutha !!!

### ISSUE THREAD

**Issue by jeevd007** [alar-dict/data#2]
Alar thara digitise aagiro niGantanna maththomme nodilla.  Sir. V. Krishna ravarige maththu nimage (Kailash Nadh) thandakke hidE kannada janada paravaagi krutagnathe galna helokke istapadtyni.  Ivaththininda nimma abhimani Naresh!!!

Do you have plans for crowd-sourcing this project to bring in more words to dictionary?  If yes, how can I contribute.  I'd love to contribute in whatever way possible I'm able to.  Please reach me at **jeevd007@gmail.com**!

**Comment by knadh** [comment]
> Alar thara digitise aagiro niGantanna maththomme nodilla. Sir. V. Krishna ravarige maththu nimage (Kailash Nadh) thandakke hidE kannada janada paravaagi krutagnathe galna helokke istapadtyni. Ivaththininda nimma abhimani Naresh!!!

Dhanyavadagalu @jeevd007  :) 

We haven't worked out a plan for crowd sourcing yet, but when we have something, we'll definitely announce here. Thank you for offering help.
