### ISSUE TITLE
Few words to add

### ISSUE THREAD

**Issue by jeevd007** [alar-dict/data#3]
Note, mostly they do exists whilst the need to given additional definition/meaning for broader usage.  Examples:
ಕಮರಿ - Cliff / Additional meaning */
ಬದ - Mesa /* word not found */
ತೆವರು - Archipelago /* word not found */
ಕೆಂಗುಂಡಿ - Atoll /* Additional meaning */
ಕಡಲ್ಕೊಳ - Lagoon /* word not found */
ಬೇರ್ಬೆಟ್ಟ - Butte /* word not found */
ನೀರ್ಗಲ್ಲೊಳೆ - Glacier /* word not found */
ಉರಿಬೆಟ್ಟ - Volcano /* word not found */
ಬಿಸಿನೀರೊಟ - Geyser /* word not found */
ನೀರೋಸರು - Oasis /* word not found */
ಕಡಲ್ಕರೆ - Beach /* Additional meaning */
ಜವುಗು - Swamp  /* Additional meaning /
I will continue to submit issues for new words to be on-boarded to this dictionary!

**Comment by knadh** [comment]
Thank you. I'll keep this issue open in-case others want to add. You can send word suggestions directly to V. Krishna at vkrishna1411@yahoo.co.in. He'll curate it and add to the corpus which will then be published on the Alar website. Hopefully in the near future, we'll have a proper system to collect and moderate entries right on the website.

**Comment by jeevd007** [comment]
Thank you Kailash, will sure drop in an email to Krishna.
